/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __HRI_RS_PACKAGE_ALL_TYPES_H__
#define __HRI_RS_PACKAGE_ALL_TYPES_H__

#include <hri_rs_package/types/type_definitions.h>


#endif /* __HRI_RS_PACKAGE_ALL_TYPES_H__ */
