/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __HRI_RS_PACKAGE_TYPE_DEFINITIONS_H__
#define __HRI_RS_PACKAGE_TYPE_DEFINITIONS_H__


#endif /* __HRI_RS_PACKAGE_TYPE_DEFINITIONS_H__ */
